### ISSUE TITLE
Nvidia GPU not detected on Debian

### ISSUE THREAD

**Issue by MrDowntempo** [lmstudio-ai/.github#53]
I'm running Debian 12.5 Bookworm. Using LM Studio 2.23 I'm anew user, coming from Ollama which does use my GPU with CUDA successfully. I have a 2080 TI. The check box for GPU Acceleration is disabled, and it states "We are unable to detect any compatible GPUs on your machine..." I've been unable to discover, on my own, any where that I might configure or fix this issue.

Here is some output from when the program starts, It confirms at least that the GPU isn't detected:

https://pastebin.com/4ek8fyKd

**Comment by yagil** [comment]
Thanks for the bug report @MrDowntempo . Are you able to try 0.2.24? Available on lmstudio.ai

**Comment by MrDowntempo** [comment]
Wow, that was a fast update! Coulda sworn I was on the latest (and the check for updates button didn't see the new one eirther) Anyways, I just installed 0.2.24 and the checkbox is still grayed out, and I see this when starting up:

```
14:56:18.946 › Manifest for backend 'CUDA llama.cpp' requires gpu acceleration, but GPU survey on hardware was unsuccesful with message 'Error trying to query CUDA gpus: No CUDA devices found!'!
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[744472:0525/145619.063924:ERROR:gpu_memory_buffer_support_x11.cc(49)] dri3 extension not supported.
14:56:19.221 › Manifest for backend 'OpenCL llama.cpp' requires gpu acceleration, but GPU survey on hardware was unsuccesful with message 'Error trying to query OpenCL gpus: No OpenCL platforms found!'!
```

**Comment by MrDowntempo** [comment]
I have found a workaround. If I run as root with the --no-sandbox flag and then close that out, I can then run the lmstudio as a regular used and my card is detected. This works for a while, but eventually I'll run LM Studio again my card won't be found. At which point, I have to run as root (iwith sudo or doas) and the no-sanbox flag once more to get it working again.
